---
title: Bestuur een verkeerslicht met Python
hero_image: afbeeldingen / banner.png
description: Leer een verkeerslicht te besturen en te programmeren met behulp van Python
theme: rood
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: "fysiek computergebruik"
technologies: "elektronica, fysieke computergebruik, python"
site_areas: ""
steps:
  - 
    title: Invoering
  - 
    title: Wat je nodig zult hebben
  - 
    title: Verbind de LED's
  - 
    title: Bedien de LED's
  - 
    title: Volgorde verkeerslichten
