---
title: Bestuur een verkeerslicht met Python
hero_image: images/banner.png
description: Leer een verkeerslicht te besturen en te programmeren met behulp van Python
listed: false
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introductie
  - 
    title: Wat heb je nodig
  - 
    title: Verbind de LED's
  - 
    title: Bestuur de LED's
