---
title: Traffic Lights with Python
hero_image: images/banner.png
description: Learn to control traffic light LEDs and code a traffic lights sequence
  using Python
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
- title: Introduction
  completion: engaged
- title: Connect the LEDs
- title: Control the LEDs
  completion: internal
- title: Traffic lights sequence
