title: traffic-lights-python
hero_image: images/banner.png
description: traffic-lights-python description
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: "physical computing"
technologies: "electronics, physical computing, python"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Connect the LEDs
  - title: Control the LEDs
  - title: Traffic lights sequence
