---
title: Traffic Lights with Python
hero_image: images/banner.png
description: पायथन के उपयोग से ट्रैफिक लाइट अनुक्रम को नियंत्रित करना सीखें
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: परिचय
  - 
    title: Connect the LEDs
  - 
    title: Control the LEDs
  - 
    title: Traffic lights sequence
