---
title: पायथन का उपयोग करते हुए एक ट्रैफिक लाइट अनुक्रम को नियंत्रित करें
hero_image: images/banner.png
description: पायथन के उपयोग से ट्रैफिक लाइट अनुक्रम को नियंत्रित करना सीखें
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: "physical computing"
technologies: "electronics, physical computing, python"
site_areas: ""
steps:
  - 
    title: परिचय
  - 
    title: आपको किन चीजों की आवश्यकता होगी
  - 
    title: एलईडी को जोडे
  - 
    title: एलईडी को नियंत्रित करें
  - 
    title: ट्रैफिक लाइट अनुक्रम
