---
title: Pythonによる信号灯
hero_image: images/banner.png
description: 信号灯のLEDを制御する方法と、Pythonを使用して信号灯のシーケンスを記述する方法
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: 前書き
  - 
    title: 必要なもの
  - 
    title: LEDを操作する
  - 
    title: 信号機を決まった順に点灯させる
