---
title: Control a Traffic Lights Sequence with Python
hero_image: images/banner.png
description: 信号灯のLEDを制御する方法と、Pythonを使用して信号灯のシーケンスを記述する方法
listed: false
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: 前書き
  - 
    title: あなたが必要とするもの
  - 
    title: LEDを接続する
  - 
    title: LEDの制御
