---
title: Traffic Lights with Python
hero_image: изображения / banner.png
description: Научете се да управлявате светодиодите със светофар и да кодирате последователността на светофарите с помощта на Python
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Въведение
  - 
    title: Connect the LEDs
  - 
    title: Control the LEDs
  - 
    title: Traffic lights sequence
