---
title: Traffic Lights with Python
hero_image: images/banner.png
description: آموزش کنترل LEDهای چراغ راهنمایی و کدنویسی آن با استفاده از پایتون
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: مقدمه
  - 
    title: Connect the LEDs
  - 
    title: Control the LEDs
  - 
    title: Traffic lights sequence
