---
title: Traffic Lights with Python
hero_image: images/banner.png
description: آموزش کنترل چراغ های چراغ راهنمایی و کد نویسی چراغ راهنمایی با استفاده از پایتون
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: مقدمه
  - 
    title: LEDها را وصل کنید
  - 
    title: کنترل LEDها
  - 
    title: ترتیب چراغ راهنمایی
