---
title: Steuere eine Verkehrsampel-Sequenz mit Python
hero_image: images/banner.png
description: Lerne die LEDs einer Verkehrsampel zu steuern und eine Lichtreihenfolge
  mit Python zu programmieren
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: electronic-components, python
site_areas: jam
hardware: electronic-components
software: python
version: 4
last_tested: 2017-01-01
steps:
- title: Einleitung
- title: Was du brauchen wirst
- title: Verbinde die LEDs
- title: Steuere die LEDs
- title: Ampel Sequenz
