---
title: Steuere eine Verkehrsampel-Sequenz mit Python
hero_image: Bilder/Banner.png
description: Lerne die LEDs einer Verkehrsampel zu steuern und eine Lichtreihenfolge mit Python zu programmieren
theme: rot
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: Programmierung-0, Phys-Comp-0
interests: "physikalische Datenverarbeitung"
technologies: "Elektronik, physikalische EDV, Python"
site_areas: ""
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: Verbinde die LEDs
  - 
    title: Steuere die LEDs
  - 
    title: Ampel Sequenz
