---
title: Steuern Sie eine Verkehrsampel Sequenz mit Python
hero_image: Bilder/Banner.png
description: Lernen Sie die LEDs einer Verkehrsampel zu steuern und eine Lichtreihenfolge mit Python zu programmieren
theme: rot
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: Programmierung-0, Phys-Comp-0
interests: "physikalische Datenverarbeitung"
technologies: "Elektronik, physikalische Datenverarbeitung, Python"
site_areas: ""
steps:
  - 
    title: Einleitung
  - 
    title: Was Sie brauchen werden
  - 
    title: Verbinde die LEDs
  - 
    title: Steuere die LEDs
  - 
    title: Ampel Sequenz
