---
title: یک ترتیب چراغ های ترافیکی را با پایتون کنترل کنید
hero_image: images / banner.png
description: یاد بگیرید برای کنترل چراغ های چراغ ترافیک و یک دنباله چراغ راهنمایی با استفاده از پایتون کد کنید
theme: سرخ
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0، phys-comp-0
interests: "محاسبات فیزیکی"
technologies: "الکترونیک، محاسبات فیزیکی، پایتون"
site_areas: ""
steps:
  - 
    title: معرفی
  - 
    title: آنچه شما نیاز دارید
  - 
    title: LED ها را وصل کنید
  - 
    title: کنترل LED ها
  - 
    title: ترتیب چراغ راهنمایی
