---
title: A jelzőlámpa sorrendjének vezérlése Pythonnal
hero_image: images / banner.png
description: Tanuld meg szabályozni a jelzőlámpák fényeit és kódold a forgalmi jelzőt a Python segítségével
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: "physical computing"
technologies: "electronics, physical computing, python"
site_areas: ""
steps:
  - 
    title: Bevezetés
  - 
    title: Amire szükséged lesz
  - 
    title: Csatlakoztasd a LED-eket
  - 
    title: Vezéreld a LED-eket
  - 
    title: A közlekedési lámpa sorrendje
