---
title: Közlekedési lámpák Pythonnal
hero_image: images/banner.png
description: Tanulj meg egy LED-ekből épített jelzőlámpát vezérlni és programozni Python-nal
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Bevezetés
  - 
    title: Csatlakoztasd a LED-eket
  - 
    title: Vezéreld a LED-eket
  - 
    title: Közlekedési lámpák ciklusa
