---
title: A jelzőlámpa sorrendjének vezérlése Pythonnal
hero_image: images / banner.png
description: Tanuld meg szabályozni a jelzőlámpák fényeit és kódold a forgalmi jelzőt a Python segítségével
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: electronic-components, python
site_areas: jam
hardware: electronic-components
software: python
version: 4
last_tested: 2017-01-01
steps: 
-
title: Bevezetés
-
title: Amire szükséged lesz
-
title: Csatlakoztasd a LED-eket
-
title: Vezéreld a LED-eket
-
title: A közlekedési lámpa sorrendje