---
title: Contrôler une séquence de feux de circulation avec Python
hero_image: images/banner.png
description: Apprenez à contrôler les DELs du feu et à coder une séquence de feux de signalisation avec Python
listed: false
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Ce dont vous aurez besoin
  - 
    title: Connectez les DELs
  - 
    title: Contrôlez les DELs
