---
title: Contrôler une séquence de feux de signalisation avec Python
hero_image: images/banner.png
description: Apprenez à contrôler les LEDs du feu et à coder une séquence de feux
  de signalisation avec Python
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: electronic-components, python
site_areas: jam
hardware: electronic-components
software: python
version: 4
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Ce dont vous aurez besoin
- title: Connectez les LEDs
- title: Contrôlez les LEDs
- title: Séquence de feux de signalisation
