---
title: Contrôler une séquence de feux de signalisation avec Python
hero_image: images / banner.png
description: Apprenez à contrôler les LEDs du feu et à coder une séquence de feux de signalisation avec Python
theme: rouge
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programmation-0, phys-comp-0
interests: "informatique physique"
technologies: "électronique, informatique physique, python"
site_areas: ""
steps:
  - 
    title: introduction
  - 
    title: Ce dont tu auras besoin
  - 
    title: Connectez les LEDs
  - 
    title: Contrôler les LEDs
  - 
    title: Séquence de feux de signalisation
