---
title: Controlla un semaforo con Python
hero_image: images/banner.png
description: Impara a controllare i semafori e crea una sequenza di luci con Python
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: "physical computing"
technologies: "electronics, physical computing, python"
site_areas: ""
steps:
  -
    title: Introduzione
  -
    title: Cosa ti serve
  -
    title: Collega i LED
  -
    title: Controlla i LED
  -
    title: La sequenza del semaforo
